// <auto-generated />
namespace MvcApplication2.Repository.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class BusinessCard : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BusinessCard));
        
        string IMigrationMetadata.Id
        {
            get { return "201406191740070_BusinessCard"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
